// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvuKIYsywe_qvs9QsH4M7a_vFZdo6Jcz4',
    appId: '1:518326819317:web:10f41910383b68b52368bc',
    messagingSenderId: '518326819317',
    projectId: 'caregiver-754a6',
    authDomain: 'caregiver-754a6.firebaseapp.com',
    databaseURL: 'https://caregiver-754a6-default-rtdb.firebaseio.com',
    storageBucket: 'caregiver-754a6.appspot.com',
    measurementId: 'G-PHRQD736KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYyyKmOJbCIYdGlQ4H4tB_h7AX_4ISAk',
    appId: '1:518326819317:android:70cfab3a286292822368bc',
    messagingSenderId: '518326819317',
    projectId: 'caregiver-754a6',
    databaseURL: 'https://caregiver-754a6-default-rtdb.firebaseio.com',
    storageBucket: 'caregiver-754a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC51Y3oaL5Y9czD-3sk6XaxJGPcxj7XfMA',
    appId: '1:518326819317:ios:87c2c49e79dcc2cb2368bc',
    messagingSenderId: '518326819317',
    projectId: 'caregiver-754a6',
    databaseURL: 'https://caregiver-754a6-default-rtdb.firebaseio.com',
    storageBucket: 'caregiver-754a6.appspot.com',
    iosClientId: '518326819317-n08dde3qoatau0ehc3kphfu7bvqg3osk.apps.googleusercontent.com',
    iosBundleId: 'com.example.caregiverApp',
  );
}
